export const LOGIN_TOKEN = 'login/token'
export const REMEMBER_PASWWORD = 'remerber/password'
export const USER_INFO = 'user/info'
export const USER_ID = 'user/id'
export const MENU = 'menu'
export const TAB_LIST= 'tablist'